In [1]:
from utils import io
from data.processors import processors

##### Test load_data

In [2]:

data = io.load_data(r'../data/datasets/era5_multi-level-2025-08-14_20-00.nc')
data

<xarray.Dataset> Size: 154MB
Dimensions:         (valid_time: 1, pressure_level: 37, latitude: 721,
                     longitude: 1440)
Coordinates:
    number          int64 8B ...
  * valid_time      (valid_time) datetime64[ns] 8B 2025-08-14T20:00:00
  * pressure_level  (pressure_level) float64 296B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude        (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude       (longitude) float64 12kB 0.0 0.25 0.5 ... 359.2 359.5 359.8
    expver          <U4 16B ...
Data variables:
    t               (valid_time, pressure_level, latitude, longitude) float32 154MB dask.array<chunksize=(1, 19, 361, 720), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-08-20T18:37 GRIB to CDM+CF via cfgrib-0.9.1...

##### Test get_dimensions

In [3]:
dims =io.get_dimensions(data)
dims

{'valid_time': 1, 'pressure_level': 37, 'latitude': 721, 'longitude': 1440}

##### Test get_global_attrs

In [4]:
global_attrs = io.get_global_attrs(data)
global_attrs

{'GRIB_centre': 'ecmf',
 'GRIB_centreDescription': 'European Centre for Medium-Range Weather Forecasts',
 'GRIB_subCentre': np.int64(0),
 'Conventions': 'CF-1.7',
 'institution': 'European Centre for Medium-Range Weather Forecasts',
 'history': '2025-08-20T18:37 GRIB to CDM+CF via cfgrib-0.9.15.0/ecCodes-2.42.0 with {"source": "tmpajgl9f3k/data.grib", "filter_by_keys": {"stream": ["oper"], "stepType": ["instant"]}, "encode_cf": ["parameter", "time", "geography", "vertical"]}'}

##### Test get_variable_and_attrs

In [5]:
variable_attrs = io.get_variable_and_attrs(data)
variable_attrs

{'t': {'GRIB_paramId': np.int64(130),
  'GRIB_dataType': 'an',
  'GRIB_numberOfPoints': np.int64(1038240),
  'GRIB_typeOfLevel': 'isobaricInhPa',
  'GRIB_stepUnits': np.int64(1),
  'GRIB_stepType': 'instant',
  'GRIB_gridType': 'regular_ll',
  'GRIB_uvRelativeToGrid': np.int64(0),
  'GRIB_NV': np.int64(0),
  'GRIB_Nx': np.int64(1440),
  'GRIB_Ny': np.int64(721),
  'GRIB_cfName': 'air_temperature',
  'GRIB_cfVarName': 't',
  'GRIB_gridDefinitionDescription': 'Latitude/Longitude Grid',
  'GRIB_iDirectionIncrementInDegrees': np.float64(0.25),
  'GRIB_iScansNegatively': np.int64(0),
  'GRIB_jDirectionIncrementInDegrees': np.float64(0.25),
  'GRIB_jPointsAreConsecutive': np.int64(0),
  'GRIB_jScansPositively': np.int64(0),
  'GRIB_latitudeOfFirstGridPointInDegrees': np.float64(90.0),
  'GRIB_latitudeOfLastGridPointInDegrees': np.float64(-90.0),
  'GRIB_longitudeOfFirstGridPointInDegrees': np.float64(0.0),
  'GRIB_longitudeOfLastGridPointInDegrees': np.float64(359.75),
  'GRIB_missingValue':

##### Test wrap_longitude

In [6]:
data = processors.wrap_longitude(data)
data

<xarray.Dataset> Size: 154MB
Dimensions:         (valid_time: 1, pressure_level: 37, latitude: 721,
                     longitude: 1440)
Coordinates:
    number          int64 8B ...
  * valid_time      (valid_time) datetime64[ns] 8B 2025-08-14T20:00:00
  * pressure_level  (pressure_level) float64 296B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude        (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
    expver          <U4 16B ...
  * longitude       (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
Data variables:
    t               (valid_time, pressure_level, latitude, longitude) float32 154MB dask.array<chunksize=(1, 19, 361, 720), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-08-20T18:37 GRIB to CDM+CF via cfgrib-0.9.1...

##### Test extract_lat_lon_coordinates

In [7]:
lat_lon, lat_lon_norm = processors.extract_lat_lon_coordinates(data)
lat_lon

dask.array<stack, shape=(1038240, 2), dtype=float64, chunksize=(1038240, 1), chunktype=numpy.ndarray>

In [8]:
lat_lon.shape

(1038240, 2)

In [9]:
lat_lon[0].compute()

array([  90., -180.])

##### Test extract_time_coordinates

In [10]:
time_coords = processors.extract_time_coordinates(data, "valid_time")
time_coords

dask.array<array, shape=(1,), dtype=float64, chunksize=(1,), chunktype=numpy.ndarray>

##### Test extract_other_coordinates

In [11]:
others, norm_others = processors.extract_other_coordinates(data, ["pressure_level"])
others.compute()

array([[1000.],
       [ 975.],
       [ 950.],
       [ 925.],
       [ 900.],
       [ 875.],
       [ 850.],
       [ 825.],
       [ 800.],
       [ 775.],
       [ 750.],
       [ 700.],
       [ 650.],
       [ 600.],
       [ 550.],
       [ 500.],
       [ 450.],
       [ 400.],
       [ 350.],
       [ 300.],
       [ 250.],
       [ 225.],
       [ 200.],
       [ 175.],
       [ 150.],
       [ 125.],
       [ 100.],
       [  70.],
       [  50.],
       [  30.],
       [  20.],
       [  10.],
       [   7.],
       [   5.],
       [   3.],
       [   2.],
       [   1.]], dtype=float32)

##### Test extract_variables

In [12]:
variables, norm_variables = processors.extract_variables(data, ["t"])
variables

dask.array<stack, shape=(38414880, 1), dtype=float32, chunksize=(4152960, 1), chunktype=numpy.ndarray>

In [13]:
variables.shape

(38414880, 1)

In [14]:
variables.shape[0]/lat_lon.shape[0]

37.0

The shape is N_Sensors x N_Variables

##### Test keep_coords

In [15]:
data = processors.keep_coords(data, ['latitude', 'longitude', 'valid_time', 'pressure_level'])
data

<xarray.Dataset> Size: 154MB
Dimensions:         (valid_time: 1, pressure_level: 37, latitude: 721,
                     longitude: 1440)
Coordinates:
  * valid_time      (valid_time) datetime64[ns] 8B 2025-08-14T20:00:00
  * pressure_level  (pressure_level) float64 296B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude        (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude       (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
Data variables:
    t               (valid_time, pressure_level, latitude, longitude) float32 154MB dask.array<chunksize=(1, 19, 361, 720), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-08-20T18:37 GRIB to CDM+CF via cfgrib-0.9.1...

##### test spatial_mask

In [16]:
mask, indices = processors.spatial_mask(data, 't', 319.62665)

In [17]:
mask.shape

(1, 37, 721, 1440)

In [18]:
indices.compute()

array([[339312]])

In [19]:
variables[339312].compute()

array([319.62665], dtype=float32)

In [20]:
lat_lon[339312].compute()

array([31.25, 48.  ])

In [21]:
data.t.sel(latitude=lat_lon[339312][0], longitude=lat_lon[339312][1]).compute()

<xarray.DataArray 't' (valid_time: 1, pressure_level: 37)> Size: 148B
array([[319.62665, 318.1836 , 316.28915, 313.9281 , 311.5559 , 309.175  ,
        306.81024, 304.43073, 302.03864, 299.6346 , 297.13257, 291.81625,
        286.09735, 280.21045, 273.77695, 270.64056, 267.1399 , 263.78586,
        256.94257, 248.57625, 239.44203, 233.21777, 226.97302, 219.48534,
        212.24078, 203.32178, 192.66716, 195.29572, 210.53502, 217.39568,
        222.16338, 230.08891, 236.44788, 239.60799, 252.00679, 255.76465,
        256.40704]], dtype=float32)
Coordinates:
  * valid_time      (valid_time) datetime64[ns] 8B 2025-08-14T20:00:00
  * pressure_level  (pressure_level) float64 296B 1e+03 975.0 950.0 ... 2.0 1.0
    latitude        float64 8B 31.25
    longitude       float64 8B 48.0
Attributes: (12/31)
    GRIB_paramId:                             130
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      1038240
    GRIB_typeOfLevel:                         isobaricInhPa
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_shortName:                           t
    GRIB_totalNumber:                         0
    GRIB_units:                               K
    long_name:                                Temperature
    units:                                    K
    standard_name:                            air_temperature

In [22]:
variables.shape

(38414880, 1)

In [23]:
lat_lon_norm.shape

(1038240, 2)

In [24]:
others.shape

(37, 1)

In [25]:
import dask.array as darray

space_throughPressure = darray.repeat(lat_lon_norm, others.shape[0], axis=0)
space_throughPressure.shape


(38414880, 2)

In [26]:
lvls_throughSpace = darray.repeat(norm_others, lat_lon_norm.shape[0], axis=0)
lvls_throughSpace.shape

(38414880, 1)

In [27]:
space_throughPressure = darray.tile(lat_lon_norm, (norm_others.shape[0],1))
space_throughPressure.shape

(38414880, 2)

In [28]:
coords = darray.hstack([space_throughPressure, lvls_throughSpace])
coords.shape

(38414880, 3)

In [29]:
variables[0].compute().item()

272.79266357421875

In [30]:
coords[0].compute()

array([ 1.57079633, -3.14159265,  1.        ])

In [31]:
maximum = data.t.data.max().compute().item()
minimum = data.t.data.min().compute().item()
value = variables[0].compute().item()
maximum, minimum, value

(319.62664794921875, 179.7404022216797, 272.79266357421875)

In [32]:
lat = lat_lon[0,0].compute().item()
lon = lat_lon[0,1].compute().item()
other = others[0].compute().item()
lat, lon, other

(90.0, -180.0, 1000.0)

In [33]:
data.t.sel(latitude=lat, longitude=lon, pressure_level=other).compute().item()

272.79266357421875

In [34]:
data.t.isel(latitude=0, longitude=0, pressure_level=0).compute().item()

272.79266357421875

In [35]:
darray.arange(time_coords.shape[0]).compute().item()

0

In [36]:
import torch
from torch.utils.data import DataLoader
from data.datamodules.datasets.troposphere_3d import ERA5Troposphere3D


In [37]:
ds = ERA5Troposphere3D(r'../data/datasets/era5_multi-level-2025-08-14_20-00.nc', batch_size=10000)

In [38]:
loader = DataLoader(ds, batch_size=4, shuffle=True)

In [39]:
lat_lon_batch, pressure_batch, time_batch, variable_batch = next(iter(loader))

lat_lon_batch.shape

<class 'int'>


AssertionError: 

In [ ]:
pressure_batch.shape

In [ ]:
time_batch.shape

In [ ]:
variable_batch.shape