In [1]:
import torch
import inspect
from models.coordinate_models.core import embeddings


In [2]:

functions = [name for name, obj in inspect.getmembers(embeddings, inspect.isfunction)]
classes = [name for name, obj in inspect.getmembers(embeddings, inspect.isclass)]

print("Functions:", functions)
print("Classes:", classes)

Functions: ['get_embedding', 'register_embedding']
Classes: ['DoubleFourierSphericalEmbedding', 'GaussianFourierEmbedding', 'PositionalEmbedding', 'SphericalCartesianEmbedding', 'SphericalCartesianPlusEmbedding', 'SphericalGridEmbedding', 'SphericalMultiScaleEmbedding', 'SphericalMultiScalePlusEmbedding']


In [3]:
# Example coordinates (latitude, longitude)
coords = torch.tensor([
    [43.6532, -79.3832],  # Toronto
    [-25.7128, 174.0060],  # NYC
    [51.5074, -0.1278]    # London
], dtype=torch.float32)

# Convert degrees to radians
coords_rad = coords * (torch.pi / 180)

print("Coordinates in radians:")
print(coords_rad)

Coordinates in radians:
tensor([[ 7.6189e-01, -1.3855e+00],
        [-4.4877e-01,  3.0370e+00],
        [ 8.9897e-01, -2.2305e-03]])


## DoubleFourierSphericalEmbedding

In [4]:
print(embeddings.DoubleFourierSphericalEmbedding.__init__.__doc__)


        Initialize the DoubleFourierSphericalEmbedding module.

        This module calculates embeddings for spherical coordinates following the paper
        https://arxiv.org/pdf/2306.17624

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_lat_min (float): The minimum radius of the latitude sphere.
            r_lon_min (float): The minimum radius of the longitude sphere.
            r_max (float, optional): The maximum radius of the spheres. Defaults to 1.0.
        


In [5]:
embedding = embeddings.DoubleFourierSphericalEmbedding(5, 0.01,0.01, 1.0)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 120])
Embedded coordinates:
tensor([[ 7.6188e-03,  2.4091e-02,  7.6116e-02,  2.3861e-01,  6.9029e-01,
          9.9997e-01,  9.9971e-01,  9.9710e-01,  9.7112e-01,  7.2353e-01,
         -1.3855e-02, -4.3799e-02, -1.3811e-01, -4.2425e-01, -9.8288e-01,
          9.9990e-01,  9.9904e-01,  9.9042e-01,  9.0555e-01,  1.8424e-01,
          9.9988e-01,  9.9901e-01,  9.9039e-01,  9.0552e-01,  1.8423e-01,
         -1.3854e-02, -4.3798e-02, -1.3810e-01, -4.2424e-01, -9.8285e-01,
          7.6181e-03,  7.6115e-03,  7.5458e-03,  6.8992e-03,  1.4037e-03,
         -1.0556e-04, -3.3370e-04, -1.0522e-03, -3.2323e-03, -7.4884e-03,
          9.9961e-01,  9.9875e-01,  9.9013e-01,  9.0528e-01,  1.8419e-01,
         -1.3851e-02, -4.3787e-02, -1.3807e-01, -4.2413e-01, -9.8260e-01,
          2.4088e-02,  2.4068e-02,  2.3860e-02,  2.1815e-02,  4.4385e-03,
         -3.3377e-04, -1.0552e-03, -3.3271e-03, -1.0221e-02, -2.3678e-02,
          9.9700e-01,  

## GaussianFourierEmbedding

In [6]:
print(embeddings.GaussianFourierEmbedding.__init__.__doc__)


        Initializes the Gaussian Fourier Embedding module. following the paper https://arxiv.org/abs/2006.10739

        Args:
            input_dim (int): The input dimension.
            mapping_dim (int): The mapping dimension.
            scale (float): The scale parameter.
        


In [7]:
embedding = embeddings.GaussianFourierEmbedding(2, 64, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 64])
Embedded coordinates:
tensor([[ 0.4914,  0.9723,  0.2648, -0.3277, -0.9231,  0.9848,  0.6912, -0.9812,
          0.1030,  0.5375,  0.7421, -0.9631, -0.1577,  0.9413, -0.4537, -0.3934,
          0.4061,  0.8589, -0.8666, -0.8890, -0.1806, -0.9497, -0.8621,  0.3376,
          0.2624,  0.9953,  0.5642,  0.8161,  0.9495, -0.0553, -0.9996,  0.9352,
          0.8709,  0.2336,  0.9643, -0.9448, -0.3845,  0.1740,  0.7226,  0.1929,
         -0.9947,  0.8432, -0.6703, -0.2692, -0.9875, -0.3376, -0.8912, -0.9194,
          0.9138, -0.5122,  0.4991,  0.4578, -0.9836,  0.3133, -0.5068, -0.9413,
         -0.9650,  0.0964, -0.8256, -0.5778, -0.3138, -0.9985, -0.0296, -0.3542],
        [ 0.9444, -0.9609, -0.6050,  0.0235, -0.5969, -0.7588, -0.9910, -0.6692,
         -0.3336,  0.9955, -0.3444, -0.2140,  0.2975,  0.9253, -0.6140,  0.9740,
          0.8861, -0.8307,  0.8781,  0.5555, -0.3185,  0.1353,  0.8549, -0.1121,
         -0.8036, -0

## PositionalEmbedding

### mapping more than 1

In [8]:
print(embeddings.PositionalEmbedding.__init__.__doc__)


        Initializes the Positional Embedding module.

        Args:
            input_dim (int): The input dimension.
            mapping_dim (int): The mapping dimension.
            scale (float): The scale parameter.

        Following the paper https://arxiv.org/abs/2006.10739
        


In [9]:
embedding = embeddings.PositionalEmbedding(2, 64, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 128])
Embedded coordinates:
tensor([[-7.1327e-01, -6.3105e-01, -5.3837e-01, -4.3573e-01, -3.2391e-01,
         -2.0399e-01, -7.7394e-02,  5.4097e-02,  1.8832e-01,  3.2274e-01,
          4.5444e-01,  5.8017e-01,  6.9635e-01,  7.9920e-01,  8.8479e-01,
          9.4920e-01,  9.8865e-01,  9.9973e-01,  9.7960e-01,  9.2624e-01,
          8.3873e-01,  7.1750e-01,  5.6460e-01,  3.8387e-01,  1.8118e-01,
         -3.5624e-02, -2.5672e-01, -4.7062e-01, -6.6455e-01, -8.2518e-01,
         -9.3946e-01, -9.9576e-01, -9.8509e-01, -9.0244e-01, -7.4809e-01,
         -5.2863e-01, -2.5767e-01,  4.4156e-02,  3.5004e-01,  6.2875e-01,
          8.4759e-01,  9.7623e-01,  9.9128e-01,  8.8108e-01,  6.4984e-01,
          3.2033e-01, -6.5998e-02, -4.5226e-01, -7.7328e-01, -9.6631e-01,
         -9.8415e-01, -8.0843e-01, -4.5969e-01, -6.2811e-04,  4.7057e-01,
          8.3844e-01,  9.9834e-01,  8.8885e-01,  5.1939e-01, -1.8125e-02,
         -5.6333e-01, -

### mapping equal to 1

In [10]:
embedding = embeddings.PositionalEmbedding(2, 1, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 2])
Embedded coordinates:
tensor([[-0.7133,  0.7009],
        [-0.8503, -0.5263],
        [ 0.7968, -0.6042]])


## SphericalCartesianEmbedding

In [11]:
print(embeddings.SphericalCartesianEmbedding.__init__.__doc__)


        Initialize the SphericalCartesianEmbedding module.

        Following the paper https://arxiv.org/pdf/2306.17624

        Output feature dimension: 3 * scale

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [12]:
embedding = embeddings.SphericalCartesianEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 6])
Embedded coordinates:
tensor([[ 0.0761,  0.6903,  0.0759,  0.4994,  0.9875,  0.1333],
        [-0.0449, -0.4339, -0.0448, -0.3909,  0.9533, -0.8961],
        [ 0.0898,  0.7827,  0.0894,  0.4872,  0.9960,  0.6224]])


## SphericalCartesianPlusEmbedding

In [13]:
print(embeddings.SphericalCartesianPlusEmbedding.__init__.__doc__)


        Initialize the SphericalCartesianPlusEmbedding module.

        Following the paper https://arxiv.org/pdf/2306.17624.
        The output_dim is 6 * scale.

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [14]:
embedding = embeddings.SphericalCartesianPlusEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 12])
Embedded coordinates:
tensor([[ 7.6116e-02,  6.9029e-01,  9.9710e-01,  7.2353e-01, -1.3811e-01,
         -9.8288e-01,  9.9042e-01,  1.8424e-01,  7.5895e-02,  4.9945e-01,
          9.8754e-01,  1.3330e-01],
        [-4.4862e-02, -4.3386e-01,  9.9899e-01,  9.0098e-01,  2.9905e-01,
          1.0442e-01,  9.5424e-01, -9.9453e-01, -4.4817e-02, -3.9090e-01,
          9.5328e-01, -8.9605e-01],
        [ 8.9776e-02,  7.8269e-01,  9.9596e-01,  6.2241e-01, -2.2305e-04,
         -2.2305e-03,  1.0000e+00,  1.0000e+00,  8.9414e-02,  4.8716e-01,
          9.9596e-01,  6.2241e-01]])


## SpericalGridEmbedding

In [15]:
print(embeddings.SphericalGridEmbedding.__init__.__doc__)


        Initializes the SphericalGridEmbedding module.

        Args:
            scale (int): The scale parameter.
            r_min (float): The minimum radius.
            r_max (float, optional): The maximum radius. Defaults to 1.0.

        Following the paper https://arxiv.org/pdf/2306.17624

        Output feature dimension: 4 * scale
        


In [16]:
embedding = embeddings.SphericalGridEmbedding(5, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 20])
Embedded coordinates:
tensor([[ 7.6116e-02,  1.3507e-01,  2.3861e-01,  4.1546e-01,  6.9029e-01,
          9.9710e-01,  9.9084e-01,  9.7112e-01,  9.0961e-01,  7.2353e-01,
         -1.3811e-01, -2.4390e-01, -4.2425e-01, -7.0266e-01, -9.8288e-01,
          9.9042e-01,  9.6980e-01,  9.0555e-01,  7.1153e-01,  1.8424e-01],
        [-4.4862e-02, -7.9720e-02, -1.4144e-01, -2.4969e-01, -4.3386e-01,
          9.9899e-01,  9.9682e-01,  9.8995e-01,  9.6832e-01,  9.0098e-01,
          2.9905e-01,  5.1419e-01,  8.1941e-01,  9.9063e-01,  1.0442e-01,
          9.5424e-01,  8.5768e-01,  5.7321e-01, -1.3659e-01, -9.9453e-01],
        [ 8.9776e-02,  1.5918e-01,  2.8047e-01,  4.8427e-01,  7.8269e-01,
          9.9596e-01,  9.8725e-01,  9.5986e-01,  8.7492e-01,  6.2241e-01,
         -2.2305e-04, -3.9665e-04, -7.0536e-04, -1.2543e-03, -2.2305e-03,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]])


## SphericalMultiScaleEmbedding

In [17]:
print(embeddings.SphericalMultiScaleEmbedding.__init__.__doc__)


        Initialize the SphericalMultiScaleEmbedding module.

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [18]:
embedding = embeddings.SphericalMultiScaleEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 10])
Embedded coordinates:
tensor([[ 0.0761,  0.6903,  0.1837,  0.1333,  0.7166,  0.1333, -0.9800, -0.7111,
          0.6837,  0.1272],
        [-0.0449, -0.4339, -0.9935, -0.8961,  0.8597, -0.8961,  0.1043,  0.0941,
         -0.4140,  0.4315],
        [ 0.0898,  0.7827,  0.9960,  0.6224,  0.6224,  0.6224, -0.0022, -0.0014,
          0.7827,  0.7827]])


## SphericalMultiScalePlusEmbedding

In [19]:
print(embeddings.SphericalMultiScalePlusEmbedding.__init__.__doc__)


        Initialize the SphericalMultiscalePlusEmbedding module.
        following the paper https://arxiv.org/pdf/2306.17624
        output_dim = 8 * scale

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [20]:
embedding = embeddings.SphericalMultiScalePlusEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 16])
Embedded coordinates:
tensor([[ 7.6116e-02,  6.9029e-01,  1.8371e-01,  1.3330e-01,  7.1660e-01,
          1.3330e-01, -9.8003e-01, -7.1115e-01,  6.8368e-01,  1.2718e-01,
          9.9710e-01,  7.2353e-01, -1.3811e-01, -9.8288e-01,  9.9042e-01,
          1.8424e-01],
        [-4.4862e-02, -4.3386e-01, -9.9353e-01, -8.9605e-01,  8.5975e-01,
         -8.9605e-01,  1.0432e-01,  9.4084e-02, -4.1401e-01,  4.3149e-01,
          9.9899e-01,  9.0098e-01,  2.9905e-01,  1.0442e-01,  9.5424e-01,
         -9.9453e-01],
        [ 8.9776e-02,  7.8269e-01,  9.9596e-01,  6.2241e-01,  6.2241e-01,
          6.2241e-01, -2.2215e-03, -1.3883e-03,  7.8269e-01,  7.8269e-01,
          9.9596e-01,  6.2241e-01, -2.2305e-04, -2.2305e-03,  1.0000e+00,
          1.0000e+00]])


In [21]:
embedding.out_features

16