In [1]:
import torch
import inspect
from models.coordinate_models.core import embeddings


In [2]:

functions = [name for name, obj in inspect.getmembers(embeddings, inspect.isfunction)]
classes = [name for name, obj in inspect.getmembers(embeddings, inspect.isclass)]

print("Functions:", functions)
print("Classes:", classes)

Functions: []
Classes: ['DoubleFourierSphericalEmbedding', 'GaussianFourierEmbedding', 'PositionalEmbedding', 'SphericalCartesianEmbedding', 'SphericalGridEmbedding', 'SphericalMultiScaleEmbedding']


In [3]:
# Example coordinates (latitude, longitude)
coords = torch.tensor([
    [43.6532, -79.3832],  # Toronto
    [-25.7128, 174.0060],  # NYC
    [51.5074, -0.1278]    # London
], dtype=torch.float32)

# Convert degrees to radians
coords_rad = coords * (torch.pi / 180)

print("Coordinates in radians:")
print(coords_rad)

Coordinates in radians:
tensor([[ 7.6189e-01, -1.3855e+00],
        [-4.4877e-01,  3.0370e+00],
        [ 8.9897e-01, -2.2305e-03]])


## DoubleFourierSphericalEmbedding

In [4]:
print(embeddings.DoubleFourierSphericalEmbedding.__init__.__doc__)


        Initialize the DoubleFourierSphericalEmbedding module.

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_lat_min (float): The minimum radius of the latitude sphere.
            r_lon_min (float): The minimum radius of the longitude sphere.
            r_max (float, optional): The maximum radius of the spheres. Defaults to 1.0.
        


In [5]:
embedding = embeddings.DoubleFourierSphericalEmbedding(3, 0.1, 1.0)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 48])
Embedded coordinates:
tensor([[ 7.6116e-02,  2.3861e-01,  6.9029e-01,  9.9710e-01,  9.7112e-01,
          7.2353e-01, -9.8288e-01, -9.8288e-01, -9.8288e-01,  1.8424e-01,
          1.8424e-01,  1.8424e-01,  1.8371e-01,  1.8371e-01,  1.8371e-01,
         -9.8003e-01, -9.8003e-01, -9.8003e-01,  1.4023e-02,  1.4023e-02,
          1.4023e-02, -7.4813e-02, -7.4813e-02, -7.4813e-02,  1.7892e-01,
          1.7892e-01,  1.7892e-01, -9.5449e-01, -9.5449e-01, -9.5449e-01,
          4.3961e-02,  4.3961e-02,  4.3961e-02, -2.3452e-01, -2.3452e-01,
         -2.3452e-01,  1.3330e-01,  1.3330e-01,  1.3330e-01, -7.1115e-01,
         -7.1115e-01, -7.1115e-01,  1.2718e-01,  1.2718e-01,  1.2718e-01,
         -6.7847e-01, -6.7847e-01, -6.7847e-01],
        [-4.4862e-02, -1.4144e-01, -4.3386e-01,  9.9899e-01,  9.8995e-01,
          9.0098e-01,  1.0442e-01,  1.0442e-01,  1.0442e-01, -9.9453e-01,
         -9.9453e-01, -9.9453e-01, -9.9353e-01, -

## GaussianFourierEmbedding

In [6]:
print(embeddings.GaussianFourierEmbedding.__init__.__doc__)


        Initializes the Gaussian Fourier Embedding module. following the paper https://arxiv.org/abs/2006.10739

        Args:
            input_dim (int): The input dimension.
            mapping_dim (int): The mapping dimension.
            scale (float): The scale parameter.
        


In [7]:
embedding = embeddings.GaussianFourierEmbedding(2, 64, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 64])
Embedded coordinates:
tensor([[-1.1023e-02,  5.7790e-01,  1.8281e-01,  2.5802e-01, -9.0447e-01,
          3.3611e-01, -1.9645e-01, -6.4572e-01,  8.6252e-01, -6.3576e-01,
         -5.5987e-01, -5.8477e-01,  5.7830e-01, -4.9759e-01,  2.7658e-02,
          9.8722e-01, -8.9405e-01, -2.0973e-01, -9.5683e-01, -8.4422e-01,
         -2.7448e-03, -9.1209e-01, -3.6832e-01,  7.2163e-01, -8.8595e-01,
         -1.0000e+00,  9.3377e-01, -8.5895e-01, -9.7047e-01, -9.7295e-01,
         -9.5655e-01,  5.8956e-01,  9.9994e-01, -8.1611e-01, -9.8315e-01,
         -9.6614e-01,  4.2653e-01, -9.4182e-01, -9.8051e-01, -7.6358e-01,
          5.0602e-01,  7.7189e-01,  8.2858e-01, -8.1120e-01, -8.1582e-01,
         -8.6741e-01,  9.9962e-01,  1.5935e-01,  4.4796e-01, -9.7776e-01,
          2.9066e-01, -5.3600e-01,  1.0000e+00,  4.0999e-01,  9.2970e-01,
          6.9228e-01,  4.6378e-01, -3.3171e-04, -3.5786e-01,  5.1206e-01,
          2.4122e-01, -2

## PositionalEmbedding

### mapping more than 1

In [8]:
print(embeddings.PositionalEmbedding.__init__.__doc__)


        Initializes the Positional Embedding module.

        Args:
            input_dim (int): The input dimension.
            mapping_dim (int): The mapping dimension.
            scale (float): The scale parameter.

        Following the paper https://arxiv.org/abs/2006.10739
        


In [9]:
embedding = embeddings.PositionalEmbedding(2, 64, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 128])
Embedded coordinates:
tensor([[-7.1327e-01, -6.3105e-01, -5.3837e-01, -4.3573e-01, -3.2391e-01,
         -2.0399e-01, -7.7394e-02,  5.4097e-02,  1.8832e-01,  3.2274e-01,
          4.5444e-01,  5.8017e-01,  6.9635e-01,  7.9920e-01,  8.8479e-01,
          9.4920e-01,  9.8865e-01,  9.9973e-01,  9.7960e-01,  9.2624e-01,
          8.3873e-01,  7.1750e-01,  5.6460e-01,  3.8387e-01,  1.8118e-01,
         -3.5624e-02, -2.5672e-01, -4.7062e-01, -6.6455e-01, -8.2518e-01,
         -9.3946e-01, -9.9576e-01, -9.8509e-01, -9.0244e-01, -7.4809e-01,
         -5.2863e-01, -2.5767e-01,  4.4156e-02,  3.5004e-01,  6.2875e-01,
          8.4759e-01,  9.7623e-01,  9.9128e-01,  8.8108e-01,  6.4984e-01,
          3.2033e-01, -6.5998e-02, -4.5226e-01, -7.7328e-01, -9.6631e-01,
         -9.8415e-01, -8.0843e-01, -4.5969e-01, -6.2811e-04,  4.7057e-01,
          8.3844e-01,  9.9834e-01,  8.8885e-01,  5.1939e-01, -1.8125e-02,
         -5.6333e-01, -

### mapping equal to 1

In [10]:
embedding = embeddings.PositionalEmbedding(2, 1, 6)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 2])
Embedded coordinates:
tensor([[-0.7133,  0.7009],
        [-0.8503, -0.5263],
        [ 0.7968, -0.6042]])


## SphericalCartesianEmbedding

In [11]:
print(embeddings.SphericalCartesianEmbedding.__init__.__doc__)


        Initialize the SphericalCatesianEmbedding module.
        Following the paper https://arxiv.org/pdf/2306.17624

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [12]:
embedding = embeddings.SphericalCartesianEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 6])
Embedded coordinates:
tensor([[ 0.0761,  0.6903,  0.0759,  0.4994,  0.9875,  0.1333],
        [-0.0449, -0.4339, -0.0448, -0.3909,  0.9533, -0.8961],
        [ 0.0898,  0.7827,  0.0894,  0.4872,  0.9960,  0.6224]])


## SpericalGridEmbedding

In [13]:
print(embeddings.SphericalGridEmbedding.__init__.__doc__)


        Initializes the SphericalGridEmbedding module.

        Args:
            scale (int): The scale parameter.
            r_min (float): The minimum radius.
            r_max (float, optional): The maximum radius. Defaults to 1.0.

        Following the paper https://arxiv.org/pdf/2306.17624
        


In [14]:
embedding = embeddings.SphericalGridEmbedding(5, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 20])
Embedded coordinates:
tensor([[ 7.6116e-02,  1.3507e-01,  2.3861e-01,  4.1546e-01,  6.9029e-01,
          9.9710e-01,  9.9084e-01,  9.7112e-01,  9.0961e-01,  7.2353e-01,
         -1.3811e-01, -2.4390e-01, -4.2425e-01, -7.0266e-01, -9.8288e-01,
          9.9042e-01,  9.6980e-01,  9.0555e-01,  7.1153e-01,  1.8424e-01],
        [-4.4862e-02, -7.9720e-02, -1.4144e-01, -2.4969e-01, -4.3386e-01,
          9.9899e-01,  9.9682e-01,  9.8995e-01,  9.6832e-01,  9.0098e-01,
          2.9905e-01,  5.1419e-01,  8.1941e-01,  9.9063e-01,  1.0442e-01,
          9.5424e-01,  8.5768e-01,  5.7321e-01, -1.3659e-01, -9.9453e-01],
        [ 8.9776e-02,  1.5918e-01,  2.8047e-01,  4.8427e-01,  7.8269e-01,
          9.9596e-01,  9.8725e-01,  9.5986e-01,  8.7492e-01,  6.2241e-01,
         -2.2305e-04, -3.9665e-04, -7.0536e-04, -1.2543e-03, -2.2305e-03,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]])


## SphericalMultiScaleEmbedding

In [15]:
print(embeddings.SphericalMultiScaleEmbedding.__init__.__doc__)


        Initialize the SphericalMultiScaleEmbedding module.
        following the paper https://arxiv.org/pdf/2306.17624

        Args:
            scale (int): The number of dimensions in the embeddings.
            r_min (float): The minimum radius of the sphere.
            r_max (float, optional): The maximum radius of the sphere. Defaults to 1.0.
        


In [19]:
embedding = embeddings.SphericalMultiScaleEmbedding(2, 0.1)

# Apply the embedding to the coordinates
embedded_coords = embedding(coords_rad)
print(f"input shape: {coords_rad.shape}")
print(f"output shape: {embedded_coords.shape}")

# Print the embedded coordinates
print("Embedded coordinates:")
print(embedded_coords)

input shape: torch.Size([3, 2])
output shape: torch.Size([3, 10])
Embedded coordinates:
tensor([[ 0.0761,  0.6903,  0.1837,  0.1333,  0.7166,  0.1333, -0.9800, -0.7111,
          0.6837,  0.1272],
        [-0.0449, -0.4339, -0.9935, -0.8961,  0.8597, -0.8961,  0.1043,  0.0941,
         -0.4140,  0.4315],
        [ 0.0898,  0.7827,  0.9960,  0.6224,  0.6224,  0.6224, -0.0022, -0.0014,
          0.7827,  0.7827]])
